version: '3.8'

services:
  app:
    build: .
    container_name: diploma_app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/diploma
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
      - OPENAI_API_KEY=${OPENAI_API_KEY}  
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/static:/app/static

  postgres:
    image: postgres:15
    container_name: diploma_postgres
    restart: always
    environment:
      POSTGRES_DB: diploma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: